config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'homes#top'
  get '/users/my_page' => 'users#mypage'
  get '/users/unsubscribe' => 'users#unsubscribe'
  get '/users/thanks' => 'users#thanks'
  get '/users/search' => 'users#search'
  resources :users, only: [:edit, :update, :destroy, :show] do
    resource :relationships, only: [:create, :update, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    delete 'decline' => 'relationships#decline'
  end
  resources :categories, only: [:index, :show]
  resources :items
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm'
  post 'contacts/back', to: 'contacts#back'
  get 'done', to: 'contacts#done'


end

app/models/relationship.rb
class Relationship < ApplicationRecord

  enum status: { unapproved: 0, allow: 1 }

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def update
    current_user.allow(params[:user_id])
    redirect_to request.referer
  end

  def decline
    current_user.decline(params[:user_id])
    redirect_to request.referer
  end

  def followings
    if params["user_id"].to_i == current_user.id
      user = User.find(params[:user_id])
      @allows = user.relationships.where(status: 1)
      @unapproved = user.relationships.where(status: 0)
    else
      redirect_to root_path
    end
  end

  def followers
    if params["user_id"].to_i == current_user.id
      user = User.find(params[:user_id])
      @unapproved = user.reverse_of_relationships.where(status: 0)
      @allows = user.reverse_of_relationships.where(status: 1)
    else
      redirect_to root_path
    end
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/followers.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-lg-12 col-md-12 col-sm-12 col-12 border-bottom">
      <h3 class="text-success">
        <strong>
          フォロワー ： <%= @allows.count %> 人
        </strong>
      </h3>
    </div>
  </div>


    <% @allows.each do |a| %>
    <div class="row mb-3 border-bottom p-3">
      <% user = a.follower %>
      <div class="col-lg-3 col-md-3 col-sm-3 col-6 d-flex align-items-center justify-content-center">
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpg', fallback:"no_image.jpg" %>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3 col-6 d-flex align-items-center justify-content-center">
        <%= link_to user_path(user.id), method: :get do %>
          <%= user.name %>
        <% end %>
      </div>
    </div>
    <% end %>


  <% if @unapproved.any? %>
    <div class="row mb-3">
      <div class="col-lg-12 col-md-12 col-sm-12 col-12 border-bottom mt-5">
        <h4>
          フォローリクエスト
        </h4>
      </div>
    </div>

    <% @unapproved.each do |u| %>
      <div class="row mb-3 border-bottom p-3">
        <% user = u.follower %>
        <div class="col-lg-3 col-md-3 col-sm-3 col-12 d-flex align-items-center justify-content-center">
          <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpg', fallback:"no_image.jpg" %>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-12 d-flex align-items-center justify-content-center">
          <%= user.name %>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-6 d-flex align-items-center justify-content-center">
          <%= link_to "許可する", user_relationships_path(user.id), method: :patch, class: "btn btn-outline-primary" %>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-6 d-flex align-items-center justify-content-center">
          <%= link_to "拒否する", user_decline_path(user.id), method: :delete, class: "btn btn-outline-danger" %>
        </div>
      </div>
    <% end %>

  <% end %>

</div>

app/views/relationships/followings.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-md-12 col-sm-12 col-12 border-bottom">
      <h3 class="text-success">
        <strong>
          フォロー中 ： <%= @allows.count %> 人
        </strong>
      </h3>
    </div>
  </div>

  <% @allows.each do |a| %>
    <div class="row mb-3 border-bottom p-3">
      <% user = a.followed %>
      <div class="col-lg-4 col-md-4 col-sm-6 col-3 d-flex align-items-center justify-content-center">
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpg', fallback:"no_image.jpg" %>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6 col-4 d-flex align-items-center justify-content-center">
        <%= link_to user_path(user.id), method: :get do %>
          <%= user.name %>
        <% end %>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12 col-5 d-flex align-items-center justify-content-center">
        <%= link_to "解除する", user_relationships_path(user.id), method: :delete, data: { confirm: "【確認】フォローを解除してもよろしいですか？" }, class: "btn btn-outline-danger" %>
      </div>
    </div>
  <% end %>

  <% if @unapproved.any? %>
    <div class="row mb-3">
      <div class="col-md-12 col-sm-12 col-12 border-bottom mt-5">
        <h4>
          リクエスト送信中 ...
        </h4>
      </div>
    </div>

    <% @unapproved.each do |u| %>
      <div class="row mb-3 border-bottom p-3">
        <% user = u.followed %>
        <div class="col-lg-4 col-md-4 col-sm-6 col-3 d-flex align-items-center justify-content-center">
          <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpg', fallback:"no_image.jpg" %>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-4 d-flex align-items-center justify-content-center">
          <%= user.name %>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-5 d-flex align-items-center justify-content-center">
          <%= link_to "取り消す", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-danger" %>
        </div>
      </div>
    <% end %>

  <% end %>

</div>