config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'homes#top'
  get '/users/my_page' => 'users#mypage'
  get '/users/unsubscribe' => 'users#unsubscribe'
  get '/users/thanks' => 'users#thanks'
  get '/users/search' => 'users#search'
  resources :users, only: [:edit, :update, :destroy, :show] do
    resource :relationships, only: [:create, :update, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    delete 'decline' => 'relationships#decline'
  end
  resources :categories, only: [:index, :show]
  resources :items
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm'
  post 'contacts/back', to: 'contacts#back'
  get 'done', to: 'contacts#done'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true

  attachment :profile_image

  def self.search(search)
      if search
        User.where(['name LIKE ?', "%#{search}%"])
      else
        User.all
      end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def allow(user_id)
    reverse_of_relationships.find_by(follower_id: user_id).update(status: 1)
  end

  def decline(user_id)
    reverse_of_relationships.find_by(follower_id: user_id).destroy
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def follower?(user)
    followers.include?(user)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_my_page_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def mypage
    @user = current_user
    @follows = @user.relationships.where(status: 1)
    @followers = @user.reverse_of_relationships.where(status: 1)
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新が完了しました。"
      redirect_to users_my_page_path
    else
      render :edit
    end
  end

  def unsubscribe
  end

  def destroy
    @user = current_user
    @user.destroy
    reset_session
    redirect_to users_thanks_path
  end

  def thanks
  end

  def search
    @users = User.search(params[:search])
  end

  def show
    user = User.find(params[:id])
    if current_user.following?(user)
      @relationship = current_user.relationships.find_by(followed_id: user.id)
      if @relationship.status == "allow"
        @user = User.find(params[:id])
        @items = @user.items
      elsif current_user.follower?(user)
        @reverse_of_relationship = current_user.reverse_of_relationships.find_by(follower_id: user.id)
        if @reverse_of_relationship.status == "allow"
          @user = User.find(params[:id])
          @items = @user.items
        else
          redirect_to users_my_page_path
        end
      else
        redirect_to users_my_page_path
      end
    elsif current_user.follower?(user)
      @reverse_of_relationship = current_user.reverse_of_relationships.find_by(follower_id: user.id)
      if @reverse_of_relationship.status == "allow"
        @user = User.find(params[:id])
        @items = @user.items
      else
        redirect_to users_my_page_path
      end
    else
      redirect_to users_my_page_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="col-md-12 col-sm-12 col-12 border-bottom">
      <h3>
        <strong>
          プロフィール編集
        </strong>
      </h3>
    </div>
  </div>

  <% if @user.errors.any? %>
    <div class="row ml-1">
      <% @user.errors.full_messages.each do |message| %>
        <p class="text-danger">
          <%= "・" + message %>
        </p>
      <% end %>
    </div>
  <% end %>

  <div class="row mb-4 ml-1">
    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
      <%= attachment_image_tag @user, :profile_image, size: '150x150', fallback: "no_image.jpg"%>
    </div>
  </div>

  <%= form_with model:@user, local:true do |f| %>

    <div class="row mb-2 ml-1">
      <%= f.label :profile_image, "プロフィール画像", class: "border-bottom" %>
    </div>
    <div class="row mb-4 ml-1">
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
    </div>

    <div class="row mb-2 ml-1">
      <%= f.label :name, "名前", class: "border-bottom" %>
    </div>
    <div class="row mb-3 ml-1">
      <%= f.text_field :name %>
    </div>

    <div class="row mb-5 ml-1">
      <%= f.submit "変更を保存", class: "btn btn-outline-success mt-5" %>
    </div>

  <% end %>

</div>

app/views/users/mypage.html.erb
<div class="container">

  <div class="row mb-5">
    <div class="col-lg-12 col-md-12 col-sm-12 col-12 text-center border-bottom">
      <h3>
        <strong>
          マイページ
        </strong>
      </h3>
    </div>
  </div>

  <div class="row justify-content-center text-success mb-3">
    <strong>
      <%= flash[:notice] %>
    </strong>
  </div>

  <div class="row justify-content-center mb-3">
    <%= attachment_image_tag @user, :profile_image, size: '150x150', format:'jpg', fallback:"no_image.jpg" %>
  </div>

  <div class="row justify-content-center mb-3">
    <h4>
      <%= @user.name %>
    </h4>
  </div>

  <div class="row justify-content-center mb-5" >
    <div class="d-flex align-items-center justify-content-center p-1">
      <i class="fas fa-cog"></i>
    </div>
    <div>
      <%= link_to "プロフィールを編集", edit_user_path(@user.id), class: "btn btn-success btn-sm" %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-6 text-center">
      <h4>
        <%= @followers.count %>
      </h4>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-6 text-center">
      <h4>
        <%= @follows.count %>
      </h4>
    </div>
  </div>

  <div class="row mb-5">
    <div class="col-lg-6 col-md-6 col-sm-6 col-6 text-center">
      <%= link_to "フォロワー", user_followers_path(@user.id), class: "btn btn-primary" %>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-6 text-center">
      <%= link_to "フォロー中", user_followings_path(@user.id), class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-12 text-right mt-5">
      <%= link_to "退会する", users_unsubscribe_path, class: "btn btn-outline-danger" %>
    </div>
  </div>

</div>

app/views/users/search.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="col-lg-12 col-md-12 col-sm-12 col-12 border-bottom">
      <h3>
        <strong>
          ユーザを探す
        </strong>
      </h3>
    </div>
  </div>

  <div class="row mb-5">
    <div>
      <%= form_tag({controller:"users",action:"search"}, method: :get) do %>
      　<%= label_tag :"名前" %>
        <%= text_field_tag :search %>
        <%= submit_tag "検索", :name => nil %>
      <% end %>
    </div>
  </div>

  <% @users.each do |user| %>
    <div class="row">
      <% unless user == current_user %>
        <div class="col-lg-3 col-md-3 col-sm-3 col-3">
          <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpg', fallback:"no_image.jpg" %>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-4 d-flex align-items-center justify-content-center">
          <%= user.name %>
        </div>
          <% if current_user.following?(user) %>
            <% @res = current_user.relationships.where(followed_id: user.id) %>
            <% @res.each do |r| %>
              <% if r.status == "unapproved" %>
                <div class="col-lg-5 col-md-5 col-sm-5 col-5 d-flex align-items-center justify-content-center">
                  <%= link_to "送信取消し", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-danger" %>
                </div>
              <% else %>
                <div class="col-lg-5 col-md-5 col-sm-5 col-5 d-flex align-items-center justify-content-center">
                  <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete, data: { confirm: "【確認】フォローを解除してもよろしいですか？" }, class: "btn btn-outline-danger" %>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <div class="col-lg-5 col-md-5 col-sm-5 col-5 d-flex align-items-center justify-content-center">
              <%= link_to "リクエスト送信", user_relationships_path(user.id), method: :post, class: "btn btn-outline-primary" %>
            </div>
          <% end %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row mb-3 border-bottom">
    <div class="col-lg-3 col-md-3 col-sm-3 col-12 mr-5">
      <%= attachment_image_tag @user, :profile_image, size: '120x120', format:'jpg', fallback:"no_image.jpg" %>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-12 d-flex align-items-center justify-content-left">
      <strong>
        <%= @user.name + " " + "さんの防災アイテム" %>
      </strong>
    </div>
  </div>

  <table class="table table-inverse table-bordered mt-5 mb-5 col-md-12">
    <thead class="bg-light">
      <tr>
        <th class="col-md-5 col-4 text-center">アイテム</th>
        <th class="col-md-3 col-3 text-center">数量</th>
        <th class="col-md-4 col-5 text-center">有効期限</th>
      </tr>
    </thead>

    <% @items.each do |item| %>
    <tbody>
      <tr>
        <td class="text-center">
        　<%= item.name %>
        </td>
        <td class="text-center">
          <%= item. amount %>
        </td>
        <% if item.expiration_date.blank? %>
        <td class="text-center">
          なし
        </td>
        <% elsif item.expiration_date <= Date.today %>
          <td class="bg-danger text-center text-white">
            <%= item.expiration_date %>
          </td>
        <% elsif item.expiration_date <= Date.today+14 %>
          <td class="bg-warning text-center">
            <%= item.expiration_date %>
          </td>
        <% else %>
          <td class="text-center">
            <%= item.expiration_date %>
          </td>
        <% end %>
      </tr>
    </tbody>
    <% end %>

  </table>

</div>

app/views/users/thanks.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-12">
    　<p>
    　  アカウントを削除しました。
    　</p>
    　<p>
    　  ご利用ありがとうございました。
      </p>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="col-lg-12 col-md-12 col-sm-12 col-12 text-center border-bottom">
      <h3>
        <strong>
          本当に退会しますか？
        </strong>
      </h3>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-12 text-center mt-5">
      <%= link_to "退会しない", users_my_page_path, class: "btn btn-outline-primary btn-lg" %>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-12 text-center mt-5">
      <%= link_to "退会する", user_path(current_user.id), method: :delete, data: { confirm: "【確認】アカウントを削除してもよろしいですか？" }, class: "btn btn-outline-danger btn-lg" %>
    </div>
  </div>

</div>