config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'homes#top'
  get '/users/my_page' => 'users#mypage'
  get '/users/unsubscribe' => 'users#unsubscribe'
  get '/users/thanks' => 'users#thanks'
  get '/users/search' => 'users#search'
  resources :users, only: [:edit, :update, :destroy, :show] do
    resource :relationships, only: [:create, :update, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    delete 'decline' => 'relationships#decline'
  end
  resources :categories, only: [:index, :show]
  resources :items
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm'
  post 'contacts/back', to: 'contacts#back'
  get 'done', to: 'contacts#done'


end

app/models/category.rb
class Category < ApplicationRecord

  has_many :items, dependent: :destroy

  validates :name, presence: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @items = @category.items.where(user_id: current_user.id)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="container">
  <div class="row mb-5 border-bottom">
    <div class="col-md-12 col-sm-12 col-12">
      <h3>
        <strong>
          マイアイテム
        </strong>
      </h3>
    </div>
  </div>

  <% @categories.each do |category| %>
    <div class="row mb-2">
      <div class="col-lg-10 col-md-10 col-sm-10 col-10">
        <%= link_to category_path(category.id), method: :get do %>
          <%= "・" + category.name %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="row mt-5 mb-4">
    <div class="d-flex align-items-center justify-content-center ml-3">
      <i class="fas fa-suitcase"></i>
    </div>
    <div class="ml-2">
      <%= link_to "アイテムを登録する", new_item_path, class: "btn btn-success" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="d-flex align-items-center justify-content-center ml-3">
      <i class="fas fa-search-plus"></i>
    </div>
    <div class="ml-2">
      <%= link_to "全アイテムを見る", items_path, class: "btn btn-primary" %>
    </div>
  </div>

</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="col-md-12 col-sm-12 col-12 border-bottom">
      <h3>
        <strong>
          <%= @category.name %>
        </strong>
      </h3>
    </div>
  </div>

  <div class="row">
    <div class="d-flex align-items-center justify-content-center ml-3">
      <i class="fas fa-suitcase"></i>
    </div>
    <div class="ml-2">
      <%= link_to "アイテムを登録する", new_item_path, class: "btn btn-success" %>
    </div>
  </div>

  <table class="table table-inverse table-bordered mt-5 mb-5 col-md-12">
    <thead class="bg-light">
      <tr>
        <th class="col-lg-5 col-md-5 col-5 text-center">アイテム</th>
        <th class="col-lg-3 col-md-3 col-2 text-center">数量</th>
        <th class="col-lg-4 col-md-4 col-5 text-center">有効期限</th>
      </tr>
    </thead>

    <% @items.each do |item| %>
      <tbody>
        <tr>
          <td class="text-center pr-4">
        　  <%= link_to item_path(item.id), method: :get do %>
             <%= item.name %>
            <% end %>
          </td>
          <td class="text-center">
            <%= item.amount %>
          </td>
          <% if item.expiration_date.blank? %>
            <td class="text-center">
              なし
            </td>
          <% elsif item.expiration_date <= Date.today %>
            <td class="bg-danger text-center text-white">
              <%= item.expiration_date %>
            </td>
          <% elsif item.expiration_date <= Date.today+14 %>
            <td class="bg-warning text-center">
              <%= item.expiration_date %>
            </td>
          <% else %>
            <td class="text-center">
              <%= item.expiration_date %>
            </td>
          <% end %>
        </tr>
      </tbody>
    <% end %>

  </table>

</div>