config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'homes#top'
  get '/users/my_page' => 'users#mypage'
  get '/users/unsubscribe' => 'users#unsubscribe'
  get '/users/thanks' => 'users#thanks'
  get '/users/search' => 'users#search'
  resources :users, only: [:edit, :update, :destroy, :show] do
    resource :relationships, only: [:create, :update, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    delete 'decline' => 'relationships#decline'
  end
  resources :categories, only: [:index, :show]
  resources :items
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm'
  post 'contacts/back', to: 'contacts#back'
  get 'done', to: 'contacts#done'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boubag</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/fda8101edf.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top: 5rem">
    <header class="mb-5">
      <nav class="navbar navbar-expand-lg navbar-light bg-warning fixed-top">
        <div class="container">
          <div class:"navbar-brand">
            <strong>
            <%= link_to "BouBag", root_path, class: "text-dark" %>
            </strong>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item d-flex align-items-center mr-2">
                <div>
                <i class="fas fa-user"></i>
                </div>
                <%= link_to "マイページ", users_my_page_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item d-flex align-items-center mr-2">
                <div>
                  <i class="fas fa-wrench"></i>
                </div>
                <%= link_to "アイテム", categories_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item d-flex align-items-center mr-2">
                <div>
                  <i class="fas fa-users"></i>
                </div>
                <%= link_to "ユーザを探す", users_search_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item d-flex align-items-center mr-2">
                <div>
                  <i class="fas fa-envelope"></i>
                </div>
                <%= link_to "お問い合わせ", new_contact_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item d-flex align-items-center">
                <div>
                  <i class="fas fa-sign-out-alt"></i>
                </div>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
            <% else %>
              <li class="nav-item d-flex align-items-center mr-2">
                <div class="mr-1">
                  <i class="fas fa-user-plus"></i>
                </div>
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item d-flex align-items-center mr-2">
                <div class="mr-1">
                  <i class="fas fa-sign-in-alt"></i>
                </div>
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
              </li>
            <% end %>
            </ul>
          </div>

        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>